### ISSUE TITLE
Cannot switch to old mode now

### ISSUE THREAD

**Issue by javorosas** [GoogleCloudPlatform/google-cloud-node#1557]
Suddenly an implementation on a server I set up one year ago stopped working. The server runs node 0.10 and gcloud 0.27. Old stack, I know. I'm working on updating it, but it's a large app and it would take a few days. In the mean time I would like to patch my previously working implementation and find out why it stopped working.

What I'm doing is a simple pipe from a gcloud `file` to express' `res`

```
bucket.file('myFile').createReadStream().pipe(res);
```

It works wonderfully on my local machine with node 0.12 and up, but not with 0.10

This is the stack trace of the exception.

```
_stream_readable.js:730
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:730:11)
    at IncomingMessage.Readable.pause (_stream_readable.js:721:3)
    at Request.pause (/Users/jrosas/dev/presto/node_modules/gcloud/node_modules/request/request.js:1405:32)
    at Request.ondata (stream.js:52:16)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/Users/jrosas/dev/presto/node_modules/gcloud/node_modules/request/request.js:962:12)
    at IncomingMessage.EventEmitter.emit (events.js:95:17)
    at flow (_stream_readable.js:596:9)
    at IncomingMessage.pipeOnReadable (_stream_readable.js:624:5)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at IncomingMessage.Readable.push (_stream_readable.js:127:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:142:22)
    at CleartextStream.socketOnData [as ondata] (http.js:1583:20)
```

**Comment by stephenplusplus** [comment]
Sorry about this... I'm not very sure where in the stack to fix this, but it seems to exist in the request module's implementation. The only luck I've had is by blocking calls to `pause` and `resume` inside of `node_modules/gcloud/node_modules/request/request.js`:

```js
Request.prototype.pause = function () {
  var self = this
  if (!self.responseContent) {
    self._paused = true
  } else {
    // self.responseContent.pause.apply(self.responseContent, arguments)
  }
}
Request.prototype.resume = function () {
  var self = this
  if (!self.responseContent) {
    self._paused = false
  } else {
    // self.responseContent.resume.apply(self.responseContent, arguments)
  }
}
```

I know that's a pretty sad solution, but hopefully it will get you by until you can upgrade Node to a more recent release.

**Comment by javorosas** [comment]
@stephenplusplus  You just saved my skin. It worked. It's going to give me more time to upgrade the node version. Thanks a lot.

**Comment by stephenplusplus** [comment]
Phew, glad it worked! Let me know if other weird things happen during the update.
