### ISSUE TITLE
BigTable getRows limit option

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/google-cloud-node#1751]
This might just be a documentation issue, but I am trying to query BigTable with a row limit:

```
const [[row]] = await table.getRows({
    decode: false,
    limit: 1,
    keys: ['foo'],
    filter: [{
      column: {
        cellLimit: 1,
      },
    }],
  });
```

and seeing this error:
```
error .google.bigtable.v2.ReadRowsRequest#numRowsLimit is not a field: undefined Error: .google.bigtable.v2.ReadRowsRequest#numRowsLimit is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/protobufjs/dist/ProtoBuf.js:2440:35)
    at MessagePrototype.set (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/protobufjs/dist/ProtoBuf.js:2434:38)
    at Message (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/protobufjs/dist/ProtoBuf.js:2363:34)
    at serialize (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/grpc/src/node/src/common.js:87:23)
    at Client.makeServerStreamRequest [as readRows] (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/grpc/src/node/src/client.js:550:19)
    at Object.request (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/@google-cloud/common/src/grpc-service.js:354:39)
    at makeRequest (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/retry-request/index.js:80:28)
    at retryRequest (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/retry-request/index.js:58:3)
    at Bigtable.GrpcService.requestStream (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/@google-cloud/common/src/grpc-service.js:369:10)
    at Instance.GrpcServiceObject.requestStream (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/@google-cloud/common/src/grpc-service-object.js:122:36)
    at Table.GrpcServiceObject.requestStream (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/@google-cloud/common/src/grpc-service-object.js:122:36)
    at Table.createReadStream (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/@google-cloud/bigtable/src/table.js:447:10)
    at Table.getRows (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/@google-cloud/bigtable/src/table.js:670:8)
    at /Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/@google-cloud/common/src/util.js:678:22
    at Table.wrapper (/Users/mata/AppHub/logrocket/node_modules/google-cloud/node_modules/@google-cloud/common/src/util.js:666:12)
    at Object.querySessionDuration$ (/Users/mata/AppHub/logrocket/packages/@apphub:logrocket-server-storage/src/BigTableStorage.js:626:22441)
    at tryCatch (/Users/mata/AppHub/logrocket/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/mata/AppHub/logrocket/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/mata/AppHub/logrocket/node_modules/regenerator-runtime/runtime.js:95:21)
    at tryCatch (/Users/mata/AppHub/logrocket/node_modules/regenerator-runtime/runtime.js:62:40)
    at invoke (/Users/mata/AppHub/logrocket/node_modules/regenerator-runtime/runtime.js:138:20)
    at /Users/mata/AppHub/logrocket/node_modules/regenerator-runtime/runtime.js:146:13
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by callmehiphop** [comment]
Thanks for reporting! Looks like I forgot to update the property name when migrating from v1 to v2 :(

I'll get a fix in asap.

**Comment by callmehiphop** [comment]
@arbesfeld I just cut a release with the fix for this. So if you update to `0.5.1` it should be sorted out. Thanks again for reporting!
