### ISSUE TITLE
CI build failures with mkdir

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#1778]
```
> npm run docs
> google-cloud-node@ docs C:\projects\google-cloud-node
> node ./scripts/docs
git rev-parse --abbrev-ref HEAD
HEAD
Building docs for bigquery@HEAD
ShellJS: internal error
Error: ENOENT, no such file or directory 'C:\projects\google-cloud-node\docs\json\bigquery\HEAD
'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:747:18)
    at mkdirSyncRecursive (C:\projects\google-cloud-node\node_modules\shelljs\src\mkdir.js:32:6)
    at C:\projects\google-cloud-node\node_modules\shelljs\src\mkdir.js:78:9
    at Array.forEach (native)
    at _mkdir (C:\projects\google-cloud-node\node_modules\shelljs\src\mkdir.js:58:8)
    at C:\projects\google-cloud-node\node_modules\shelljs\src\common.js:338:25
    at Builder.build (C:\projects\google-cloud-node\scripts\docs\builder.js:76:19)
    at build (C:\projects\google-cloud-node\scripts\docs\builder.js:441:11)
    at C:\projects\google-cloud-node\scripts\docs\builder.js:469:5
npm ERR! Windows_NT 6.3.9600
```

https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-node/build/1.0.519/job/9mgbx2cxbrecrcgq#L721

**Comment by stephenplusplus** [comment]
> hmm, that's weird. Appears to be failing on a mkdir -p. Not sure why that would happen .. I'll try and dig in.
> \- @callmehiphop

**Comment by stephenplusplus** [comment]
@callmehiphop I could be off, but it looks like it's treating the "version" of each module as `HEAD`, where I would have expected `master`. Is that an issue?

**Comment by stephenplusplus** [comment]
This is resolved, right?
