### ISSUE TITLE
Unable to run tests: Cannot find module aesCipherSuites

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#1805]
#### Environment details

  - OS: mac
  - Node.js version: latest v7 and v6
  - npm version:
  - google-cloud-node version: `master` as of right now.

#### Steps to reproduce

  1. `git clone <this repo>`
  2. `npm install`
  3. `npm run test`

```
  ....
  1) bigquery documentation should run BigQuery#createDataset examples without errors:



Cannot find module './aesCipherSuites'
  Error: Cannot find module './aesCipherSuites'
      at require (internal/module.js:20:19)
      at packages/bigquery/node_modules/@google-cloud/common/node_modules/google-auto-auth/node_modules/google-auth-library/node_modules/gtoken/node_modules/google-p12-pem/node_modules/node-forge/js/forge.js:31:14
      at Array.map (native)
      at Module.module.exports (packages/bigquery/node_modules/@google-cloud/common/node_modules/google-auto-auth/node_modules/google-auth-library/node_modules/gtoken/node_modules/google-p12-pem/node_modules/node-forge/js/forge.js:30:21)
```

Is there a setup step I am missing?

**Comment by stephenplusplus** [comment]
I haven't been able to reproduce. I'm wondering if there was an error during `npm install` that got lost in the output. Can you try clearing everything (node_modules *and* packages/*/node_modules), then trying `npm install` again? Keep an eye out for `WARN` and `ERR` log lines.

**Comment by ofrobots** [comment]
I didn't see any suspicious message during the install..

```
❯ rm -rf node_modules

~/src/google-cloud-node master
❯ npm install
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global npm@3.10.10 should be installed with -g
npm WARN prefer global jsonlint@1.6.2 should be installed with -g

> google-cloud-node@ postinstall /Users/ofrobots/src/google-cloud-node
> node ./scripts/install.js

Installing dependencies for bigquery
Installing dependencies for bigtable
Installing dependencies for common
Installing dependencies for compute
Installing dependencies for datastore
Installing dependencies for dns
Installing dependencies for google-cloud
Installing dependencies for language
Installing dependencies for logging
Installing dependencies for monitoring
Installing dependencies for prediction
Installing dependencies for pubsub
Installing dependencies for resource
Installing dependencies for speech
Installing dependencies for storage
Installing dependencies for translate
Installing dependencies for vision
All dependencies installed
google-cloud-node@ /Users/ofrobots/src/google-cloud-node
...
```

**Comment by ofrobots** [comment]
Once I removed everything from packages/*/node_modules, things work. Thanks!

**Comment by stephenplusplus** [comment]
Phew! Let me know if anything else pops up while you're in there.
