### ISSUE TITLE
Failure in npm/google-cloud@0.44.0

### ISSUE THREAD

**Issue by abawany** [GoogleCloudPlatform/google-cloud-node#1806]
Trying to upgrade from 0.41.2 to 0.44.0. No idea why this is happening.

```
/x/node_modules/google-cloud/node_modules/protobufjs/dist/protobuf.js:2472
                            throw Error(this+"#"+keyOrObj+" is not a field: undefined");
                            ^

Error: .google.logging.v2.LogEntry#type is not a field: undefined
    at Error (native)
    at MessagePrototype.set (/x/node_modules/google-cloud/node_modules/protobufjs/dist/protobuf.js:2472:35)
    at MessagePrototype.set (/x/node_modules/google-cloud/node_modules/protobufjs/dist/protobuf.js:2466:38)
    at Message (/x/node_modules/google-cloud/node_modules/protobufjs/dist/protobuf.js:2395:34)
    at ProtoBuf.Reflect.ElementPrototype.verifyValue (/x/node_modules/google-cloud/node_modules/protobufjs/dist/protobuf.js:1909:28)
    at ProtoBuf.Reflect.FieldPrototype.verifyValue (/x/node_modules/google-cloud/node_modules/protobufjs/dist/protobuf.js:3455:43)
    at MessagePrototype.set (/x/node_modules/google-cloud/node_modules/protobufjs/dist/protobuf.js:2475:59)
    at MessagePrototype.set (/x/node_modules/google-cloud/node_modules/protobufjs/dist/protobuf.js:2466:38)
    at Message (/x/node_modules/google-cloud/node_modules/protobufjs/dist/protobuf.js:2395:34)
    at serialize (/x/node_modules/google-cloud/node_modules/grpc/src/node/src/common.js:87:23)
```

**Comment by stephenplusplus** [comment]
Could you show the code that's producing the error?

**Comment by abawany** [comment]
Here is a method to duplicate the error (which isn't working for me today so I guess I will close the bug):

* Install deps (in a clean dir):
```
npm install winston
npm install winston-googlecloud
```

* Code that shows the error:
```
node
> process.env.GCLOUD_PROJECT='gcloud-project-name';
> let winston = require('winston');
> require('winston-googlecloud');
> let opts = {level: 'info', gcl_project_id: process.env.GCLOUD_PROJECT, gcl_log_name: 'some-log'};
> winston.add(winston.transports.GoogleCloudLogging, opts);
> winston.error({t: true, 'hello': 'something'});
```

On Saturday (11/19/16), this was generating the above error for me but today the log shows up in gcloud as expected. I rolled my code back already to use `gcloud@0.37.0` for now and will try to migrate to `google-cloud@latest` at some point in the future.

**Comment by stephenplusplus** [comment]
This is probably because of a change we made in our Logging module (https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1666). `winston-googlecloud` doesn't depend on a specific version of google-cloud, it just pulls the latest. If they locked down to an older version, that would work. Otherwise, they'll need to make changes to accommodate the restructure introduced in https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1666.
