### ISSUE TITLE
Error: Cannot find module '.../node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.node'

### ISSUE THREAD

**Issue by intralizee** [GoogleCloudPlatform/google-cloud-node#1820]
Hi,

I'm having an issue when using google-cloud on my server that is running Ubuntu.

#### Environment details

  - OS: Ubuntu 16.04.1 LTS
  - Node.js version: v7.2.0
  - npm version: 3.10.9
  - google-cloud-node version: 0.44.0

#### Steps to reproduce

  1. require `google-cloud`
  2. npm install
  3. node app.js

nom-debug.log contains:
```
89314 info lifecycle grpc@1.0.1~install: grpc@1.0.1
89315 verbose lifecycle grpc@1.0.1~install: unsafe-perm in lifecycle true
89316 verbose lifecycle grpc@1.0.1~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/intralizee/Psychedelices/node_modules/google-cloud/node_module$
89317 verbose lifecycle grpc@1.0.1~install: CWD: /home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc
89318 silly lifecycle grpc@1.0.1~install: Args: [ '-c', 'node-pre-gyp install --fallback-to-build' ]
89319 verbose stack Error: spawn ENOMEM
89319 verbose stack     at exports._errnoException (util.js:1022:11)
89319 verbose stack     at ChildProcess.spawn (internal/child_process.js:313:11)
89319 verbose stack     at exports.spawn (child_process.js:385:9)
89319 verbose stack     at spawn (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:21:13)
89319 verbose stack     at runCmd_ (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:247:14)
89319 verbose stack     at runCmd (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:208:5)
89319 verbose stack     at runPackageLifecycle (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:174:3)
89319 verbose stack     at Array.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
89319 verbose stack     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
89319 verbose stack     at chain (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
89320 verbose cwd /home/intralizee/Psychedelices
89321 error Linux 4.4.0-47-generic
89322 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
89323 error node v7.2.0
89324 error npm  v3.10.9
89325 error code ENOMEM
89326 error errno ENOMEM
89327 error syscall spawn
89328 error spawn ENOMEM
89329 error If you need help, you may report this error at:
89329 error     <https://github.com/npm/npm/issues>
89330 verbose exit [ 1, true ]
```

When running the server by node app.js the console outputs:
```
Error: Cannot find module '/home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc/src/node/extension_binary/grpc_node.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc/src/node/src/client.js:55:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/intralizee/Psychedelices/node_modules/google-cloud/node_modules/grpc/src/node/index.js:45:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

```

If there is anything else I can provide, let me know and thanks for the hard work!

**Comment by stephenplusplus** [comment]
This issue was moved to grpc/grpc#8860

**Comment by stephenplusplus** [comment]
Thanks for the kind words and the detailed issue! I've moved this to the grpc repo, as they should be able to get to the problem quicker.

**Comment by walshe** [comment]
also getting thin on cloud9 IDE
