### ISSUE TITLE
Speech API has required config, but not clear that it's required

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1904]
I'd expect the following to work just fine:

```js
speech.recognize(audio).then(console.log);
```

Instead I get an error:

```
> /home/jjg/node_modules/google-cloud/node_modules/@google-cloud/speech/src/index.js:656
        callback(err, null, resp);
        ^

TypeError: callback is not a function
    at /home/jjg/node_modules/google-cloud/node_modules/@google-cloud/speech/src/index.js:656:9
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

which is clearly telling me that I should be using callback style rather than promises :(

**Comment by jgeewax** [comment]
Actually, upon further inspection of index.js:656 it seems that there's an error (likely that I haven't enabled the API) and we're not doing the right thing w it.... 

```
> speech.recognize(audioFilePath, {}, console.log);
undefined
> { Error: Google Cloud Speech API has not been used in project jjg-cloud-research before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/speech.googleapis.com/overview?project=jjg-cloud-research then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
    at /home/jjg/node_modules/google-cloud/node_modules/grpc/src/node/src/client.js:417:17
  code: 7,
  metadata: Metadata { _internal_repr: { 'google.rpc.help-bin': [Object] } },
  note: 'Exception occurred in retry method that was not classified as transient' } null undefined
```

versus

```
> speech.recognize(audioFilePath, console.log);
undefined
> /home/jjg/node_modules/google-cloud/node_modules/@google-cloud/speech/src/index.js:656
        callback(err, null, resp);
        ^

TypeError: callback is not a function
    at /home/jjg/node_modules/google-cloud/node_modules/@google-cloud/speech/src/index.js:656:9
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by stephenplusplus** [comment]
I think the promise will work if you provide a config object:

speech.recognize('./audio', { ... })
  .then(...)

What we need to do is throw if a config object isn't provided.

**Comment by jgeewax** [comment]
Yep, just realized that. In the rest of the stuff we do, configs are optional. In this, they're not :(

We should make that super duper clear, and throw the right error when a config object is missing.
