### ISSUE TITLE
cloud-storage: occasional crash in gcs-resumable-upload / configstore / write-file-atomic when multiple GCS nodejs applications running

### ISSUE THREAD

**Issue by c0b** [GoogleCloudPlatform/google-cloud-node#1923]
for some node cluster (https://nodejs.org/api/cluster.html) applications design it needs to run multiple nodejs instances on the same machine, when they all can write to GCS, I found it occasionally died with this traceback; when running without cluster mode / in single nodejs instance, this doesn't reproduce

I think it's when multiple instances are doing the same renaming `gcs-resumable-upload.json.3934527893` to `gcs-resumable-upload.json` and the random string `3934527893` clashed the latter renaming would fail, and resulted the crash

```console
/node_modules/configstore/index.js:69
                                throw err;
                                ^

Error: ENOENT: no such file or directory, rename '~/.config/configstore/gcs-resumable-upload.json.3934527893' -> '~/.config/configstore/gcs-resumable-upload.json'
    at Error (native)
    at Object.fs.renameSync (fs.js:809:18)
    at Function.writeFileSync [as sync] (/node_modules/write-file-atomic/index.js:87:8)
    at Object.set (/node_modules/configstore/index.js:62:21)
    at Object.Configstore (/node_modules/configstore/index.js:27:11)
    at new Upload (/node_modules/gcs-resumable-upload/index.js:63:22)
    at Upload (/node_modules/gcs-resumable-upload/index.js:28:41)
    at File.startResumableUpload_ (/node_modules/@google-cloud/storage/src/file.js:1647:22)
    at Pumpify.<anonymous> (/node_modules/@google-cloud/storage/src/file.js:891:12)
    at emitThree (events.js:116:13)
    at Pumpify.emit (events.js:194:7)
```

I did search https://github.com/GoogleCloudPlatform/google-cloud-node/issues?q=gcs-resumable-upload but I believe this deserves a new issue.

**Comment by stephenplusplus** [comment]
In this case, it's best to manage the resumable upload manually with [`createResumableUpload`](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.45.0/storage/file?method=createResumableUpload):

```js
file.createResumableUpload(function(err, uri) {
  var writeStream = file.createWriteStream({ uri: uri })
  // or:
  bucket.upload('file.jpg', { uri: uri }, function(err) {})
})
```
