### ISSUE TITLE
Spanner on master throwing errors from GAX

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2063]
@jmuk will you try running the system tests from packages/spanner on master with the latest dependencies? It instantly throws:

```
  1) Spanner "before all" hook:
     Uncaught TypeError: Cannot read property 'apply' of undefined
      at src\admin\instance\v1\instance_admin_client.js:165:47
      at wrappedCall (node_modules\google-gax\lib\paged_iteration.js:75:12)
      at timeoutFunc (node_modules\google-gax\lib\api_callable.js:171:12)
      at repeat (node_modules\google-gax\lib\api_callable.js:235:19)
      at retryingFunc (node_modules\google-gax\lib\api_callable.js:264:7)
      at _combinedTickCallback (internal/process/next_tick.js:74:11)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by jmuk** [comment]
Created https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2066. system-test succeeds on my environment with this.

**Comment by stephenplusplus** [comment]
Thanks. So what was the problem?

**Comment by jmuk** [comment]
I actually didn't get the exact error you wrote but I see another error. But both errors would indicate that some recent changes on google-gax was incompatible with the code generated previously (we are doing this since we want to keep the major version of google-gax to be 0 for now).
