### ISSUE TITLE
Preserve missing project ID error stack trace

### ISSUE THREAD

**Issue by gajus** [GoogleCloudPlatform/google-cloud-node#2068]
I am referring to:

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/1939deaa32298b3cbe123686e5c52f480c1d7ee2/packages/common/src/util.js#L55

Error stack trace is captured at the time of constructing the `Error` instance.

As a result, the error stack trace does not relate to the origin site of the error, e.g.

```
Error: Sorry, we cannot connect to Cloud Services without a project ID. You may specify one with an environment variable named "GCLOUD_PROJECT". See https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/authentication for a detailed guide on creating an authenticated connection.
    at Object.<anonymous> (/Users/gajus/Documents/dev/applaudience/movie-editor/node_modules/google-cloud/node_modules/@google-cloud/common/src/util.js:55:29)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/gajus/Documents/dev/applaudience/movie-editor/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/gajus/Documents/dev/applaudience/movie-editor/node_modules/google-cloud/node_modules/@google-cloud/common/src/service-object.js:32:12)

```

Consider using the following approach to construct errors:

https://github.com/gajus/xfetch/blob/0d8cd012354b0bb8b67162f74b2a9e126d3bdabb/src/errors.js

**Comment by eoogbe** [comment]
Thanks for filing this issue. We agree that this would be a good issue to fix, and we invite you or another community member to contribute a pull request (PR), which we would be happy to review.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-common/issues/12.
