### ISSUE TITLE
The Spanner documentation test fails

### ISSUE THREAD

**Issue by murgatroid99** [GoogleCloudPlatform/google-cloud-node#2076]
#### Environment details

  - OS: Ubuntu
  - Node.js version: 7.6.0
  - npm version: 4.1.2
  - google-cloud-node version: HEAD

#### Steps to reproduce

  1. git clone <this repository>
  2. npm install
  3. npm test

When I run it I get this error

```
commonGrpc.Service.encodeValue_ is not a function
  TypeError: commonGrpc.Service.encodeValue_ is not a function
      at Object.encode (packages/spanner/src/codec.js:177:42)
      at Database.runStream (packages/spanner/src/database.js:603:28)
      at Database.run (packages/spanner/src/database.js:490:8)
      at Database.wrapper [as run] (packages/spanner/node_modules/@google-cloud/common/src/util.js:705:29)
      at assert-code.vm:52:10
      at ContextifyScript.Script.runInContext (vm.js:32:29)
      at ContextifyScript.Script.runInNewContext (vm.js:38:15)
      at Object.exports.runInNewContext (vm.js:69:17)
      at runCodeInSandbox (test/docs.js:293:8)
      at Context.<anonymous> (test/docs.js:194:13)
```

**Comment by stephenplusplus** [comment]
Fixing now, sorry about that!

**Comment by stephenplusplus** [comment]
Fixed in this commit: https://github.com/GoogleCloudPlatform/google-cloud-node/commit/7fb46142efb82f5105fcc5127d78b5ae09a8e1c1 -- I had to restore the `encodeValue_` method and publish it under @google-cloud/common-grpc@0.2.1.
