### ISSUE TITLE
Google Cloud Storage Issue in Electron.

### ISSUE THREAD

**Issue by Mathi05** [GoogleCloudPlatform/google-cloud-node#2085]
Hi,

I have configured google-cloud-node for cloud storage but while running an app throws an error. 

**Code:**

var gcloud = require('google-cloud');
				var storage = gcloud.storage;
				var fs = require('fs');
				var gcs = storage({
									projectId: 'test-id',
									keyFilename: './cloud_auth/keyfile.json'
								});
				

				gcs.createBucket('test-bucked', function(err, bucket) 
				{
				  if (!err) 
				  {
					// "my-new-bucket" was successfully created.
				  }
				}); 

**Error:**

Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\xampp\htdocs\projects\electron-quick-start\node_modules\google-cloud\node_modules\grpc\src\node\extension_binary\grpc_node.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\projects\electron-quick-start\node_modules\google-cloud\node_modules\grpc\src\node\src\grpc_extension.js:38:15)
    at Object.<anonymous> (C:\xampp\htdocs\projects\electron-quick-start\node_modules\google-cloud\node_modules\grpc\src\node\src\grpc_extension.js:42:3)

Please help me out. 

Thanks,

**Comment by Mathi05** [comment]
Hi,

This is working fine with,
 
var storage = require('@google-cloud/storage');

Thanks
