### ISSUE TITLE
Spanner requests failing as invalid if the project ID isn't set explicitly

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2086]
[ stephenpulsplus ]

#### To Dos

- [ ] Support automatic project ID detection in Spanner. To do that;
  - [ ] Lazily instantiate clients to prevent throwing
  - [ ] Execute callback with correct error (missing project ID error) when we can't get one, before making the request

[ /stephenplusplus ]

It seems like we're not properly constructing the request? 

I first noticed this when trying to get the schema of a table (I'd already run `gcloud config set project <myproject>`)

```js
> var gcloud = require('google-cloud');
undefined
> var spanner = gcloud.spanner();
undefined
> var instance = spanner.instance('my-instance');
undefined
> var db = instance.database('my-db');
undefined
> db.getSchema(console.log);
undefined
> { Error: Invalid GetDatabaseDdl request.
    at /usr/local/google/home/jjg/node_modules/google-cloud/node_modules/grpc/src/node/src/client.js:434:17
  code: 3,
  metadata: 
   Metadata {
     _internal_repr: 
      { 'google.rpc.badrequest-bin': [Object],
        'google.rpc.debuginfo-bin': [Object] } },
  note: 'Exception occurred in retry method that was not classified as transient' }
```

Then thought that I should try it higher up the chain...

```
> instance.exists(console.log);
undefined
> { Error: Invalid GetInstance request.
    at /usr/local/google/home/jjg/node_modules/google-cloud/node_modules/grpc/src/node/src/client.js:434:17
  code: 3,
  metadata: 
   Metadata {
     _internal_repr: 
      { 'google.rpc.badrequest-bin': [Object],
        'google.rpc.debuginfo-bin': [Object] } },
  note: 'Exception occurred in retry method that was not classified as transient' }
```

I tried re-creating the `spanner` object with an explicit project ID, and that fixed the problem.

Can we throw a better error if the project ID wasn't detected? Saying "the request was invalid" is super not helpful.

**Comment by stephenplusplus** [comment]
I'm getting quite wildly different results where that error is a dream. What version of google-cloud are you using and in what env?

0.49.0 and local for me:

```js
var gcloud = require('google-cloud')
var spanner = gcloud.spanner()
```

Prints to the console:
```sh
$ node .
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 9): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 10): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 11): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 13): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 14): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 15): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 16): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 18): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 22): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 24): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 28): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 29): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 30): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 31): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 33): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 34): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 35): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 36): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
(node:8712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 37): Error: Could not load the default credentials. Browse to https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

That is from the lines of code in the Spanner constructor that instantiates the GAX client APIs: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/dd9001637002c0c4ca5ede15ace123f341d0ebb0/packages/spanner/src/index.js#L72-L76

Each one throws multiple errors.

@jmuk @landrito -- should we expect those to throw and lazily instantiate the GAX clients from the handwritten layer, or is them throwing like mad a bug?

**Comment by jmuk** [comment]
Sorry seeing this. That looks like a bug on GAX. It should throw a single exception on such case, or just be done lazily so that the failure is reported for the first time a method is called.

Filed as https://github.com/googleapis/gax-nodejs/issues/121

cc: @lukesneeringer

**Comment by stephenplusplus** [comment]
I recall now that we decided automatic project ID detection wasn't a feature we would support for the first release of Spanner. So, this issue can evolve into:

- [ ] Support automatic project ID detection in Spanner. To do that;
  - [ ] Lazily instantiate clients to prevent throwing
  - [ ] Execute callback with correct error (missing project ID error) when we can't get one, before making the request

**Comment by stephenplusplus** [comment]
I'm going to close this issue to let the more general #1859 track it across all of our APIs that lost auto-project ID insertion when switching to GAX.
