### ISSUE TITLE
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null

### ISSUE THREAD

**Issue by intralizee** [GoogleCloudPlatform/google-cloud-node#2399]
Hi, 

I'm having issue with the latest google-cloud version in my node.js project.
Also encountering this error on my Ubuntu 16.04.2 LTS server on google cloud. 

#### Environment details

  - OS: macOS Sierra 10.12.6 Beta 
  - Node.js version: v8.1.2
  - npm version: 5.0.3
  - google-cloud-node version: 0.55.0

#### Steps to reproduce

  1. require `google-cloud`
  2. npm install
  3. see output below...

```
> grpc@1.3.7 install /Users/intralizee/Development/GitHub/Psychedelices/node_modules/google-cloud/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack TypeError: Cannot read property 'version' of null
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/intralizee/Development/GitHub/Psychedelices/node_modules/google-cloud/node_modules/node-pre-gyp/lib/util/versioning.js:270:32)
node-pre-gyp ERR! stack     at install (/Users/intralizee/Development/GitHub/Psychedelices/node_modules/google-cloud/node_modules/node-pre-gyp/lib/install.js:168:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/intralizee/Development/GitHub/Psychedelices/node_modules/google-cloud/node_modules/node-pre-gyp/lib/node-pre-gyp.js:50:37)
node-pre-gyp ERR! stack     at run (/Users/intralizee/Development/GitHub/Psychedelices/node_modules/google-cloud/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/intralizee/Development/GitHub/Psychedelices/node_modules/google-cloud/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:569:30)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:580:10)
node-pre-gyp ERR! stack     at Module.load (module.js:503:32)
node-pre-gyp ERR! stack     at tryModuleLoad (module.js:466:12)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:458:3)
node-pre-gyp ERR! System Darwin 16.7.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/intralizee/Development/GitHub/Psychedelices/node_modules/google-cloud/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/intralizee/Development/GitHub/Psychedelices/node_modules/google-cloud/node_modules/grpc
node-pre-gyp ERR! node -v v8.1.2
node-pre-gyp ERR! node-pre-gyp -v vhttps://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.34.tgz
node-pre-gyp ERR! not ok 
Cannot read property 'version' of null
```

**Comment by stephenplusplus** [comment]
I believe the problem has to do with google-cloud being a shrinkwrapped module, and there being an npm@5 bug: https://github.com/npm/npm/issues/16728

For now, downgrading to an older version of npm, or individually installing the google-cloud modules that you need, i.e. @google-cloud/storage, would be best.

**Comment by intralizee** [comment]
Thanks I'll give it a try.

**Comment by stephenplusplus** [comment]
I'm going to close, since I think that will be the best resolution we can suggest for now. Let me know if it didn't work, and we will have to figure out another way. Sorry for the trouble.
