### ISSUE TITLE
DNS Zone.import fails on default TTL

### ISSUE THREAD

**Issue by timwsuqld** [GoogleCloudPlatform/google-cloud-node#2550]
#### Environment details

  - OS: Linux
  - Node.js version: 4.2.6
  - npm version: 3.5.2
  - google-cloud-node version: 0.6.2

#### Steps to reproduce

  1. Attempt to import a zonefile with a $TTL variable
```js
require('@google-cloud/dns')();
... // fetch zone
zone.import('zonefile').then(function(data) {
  console.log(data);
});
```
zonefile
```
$TTL 3600
test.com.                            IN SOA  ns.test.com. domains.test.com. (
                                         2016102701  ; sn
                                         1d ; ref
                                         2h ; retry
                                         4w ; expiry
                                         1h ; min
)
test.com.                            A       1.2.3.4

```
Throws the error
```
/home/timw/src/zonefiles/node_modules/string-format-obj/index.js:12
  return template.replace(/{([^}]*)}/g, function (match, key) {
                 ^

TypeError: Cannot read property 'replace' of undefined
    at interpolate (/home/timw/src/zonefiles/node_modules/string-format-obj/index.js:12:18)
    at module.exports (/home/timw/src/zonefiles/node_modules/string-format-obj/index.js:8:10)
    at Function.Record.fromZoneRecord_ (/home/timw/src/zonefiles/node_modules/@google-cloud/dns/src/record.js:92:11)
    at /home/timw/src/zonefiles/node_modules/@google-cloud/dns/src/zone.js:806:37
    at Array.forEach (native)
    at /home/timw/src/zonefiles/node_modules/@google-cloud/dns/src/zone.js:805:21
    at Array.forEach (native)
    at /home/timw/src/zonefiles/node_modules/@google-cloud/dns/src/zone.js:802:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

@google-cloud/dns/src/record.js (around 92) doesn't have a record type TTL, hence the error.
```js
Record.fromZoneRecord_ = function(zone, type, bindData) {
  var typeToZoneFormat = {
    a: '{ip}',
    aaaa: '{ip}',
    cname: '{alias}',
    mx: '{preference} {host}',
    ns: '{host}',
    soa: '{mname} {rname} {serial} {retry} {refresh} {expire} {minimum}',
    spf: '{data}',
    srv: '{priority} {weight} {port} {target}',
    txt: '{txt}'
  };

  var metadata = {
    data: format(typeToZoneFormat[type.toLowerCase()], bindData),
    name: bindData.name,
    ttl: bindData.ttl
  };

  return new Record(zone, type, metadata);
};
```
The underlying dns-zonefile library understands the $TTL variable, and parses it without issues, we just need to not attempt to make a record from the $TTL variable, and instead use that as the default TTL unless it's overridden by the individual record.

The `gcloud dns record-sets import --zone-file-format` correctly understands the TTL variable and imports without an issue.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-dns#9
