### ISSUE TITLE
@google-cloud/monitoring v3 createTimeSeries timeSeries.points.TimeInterval [endTime & startTime] can't pass the element value check.

### ISSUE THREAD

**Issue by QTGate** [GoogleCloudPlatform/google-cloud-node#2600]
Hello,

- OS: Debian 
  - Node.js version: v8.4.0
  - npm version: v5.4.1
  - google-cloud-node version: v0.56.0
  - monitoring version: v.0.3.0

#### Steps to reproduce
```js
const client = require ( '@google-cloud/monitoring' ).v3.metric ( connectOption )
const formattedName = client.projectPath ( connectOption.projectId )
const timeSeries = [{
    ...
    points: [{
         interval: {
               endTime: JSON.parse ( JSON.stringify ( new Date()))
          },
          value: {
          ...
          }
      }]
}]
client.createTimeSeries ({ name: formattedName, timeSeries: timeSeries }).then (() => {
        ...
    }).catch ( err => {
        ...
    })

Error: Illegal value for endTimevalue element of type message: string (object expected)
    at fail (/home/admin/node_modules/protobufjs/dist/protobuf.js:1817:23)
    at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (/home/admin/node_modules/protobufjs/dist/protobuf.js:1913:25)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/admin/node_modules/protobufjs/dist/protobuf.js:3499:33)
    at MessagePrototype.set (/home/admin/node_modules/protobufjs/dist/protobuf.js:2493:59)
    at MessagePrototype.set (/home/admin/node_modules/protobufjs/dist/protobuf.js:2483:38)
    at Message (/home/admin/node_modules/protobufjs/dist/protobuf.js:2411:34)
    at Element.ProtoBuf.Reflect.ElementPrototype.verifyValue (/home/admin/node_modules/protobufjs/dist/protobuf.js:1925:28)
    at Field.ProtoBuf.Reflect.FieldPrototype.verifyValue (/home/admin/node_modules/protobufjs/dist/protobuf.js:3499:33)
    at MessagePrototype.set (/home/admin/node_modules/protobufjs/dist/protobuf.js:2493:59)
    at MessagePrototype.set (/home/admin/node_modules/protobufjs/dist/protobuf.js:2483:38)
```
If I change endTime to a Date object it also have error:
```js
const client = require ( '@google-cloud/monitoring' ).v3.metric ( connectOption )
const formattedName = client.projectPath ( connectOption.projectId )
const timeSeries = [{
    ...
    points: [{
         interval: {
               endTime: new Date()
          },
          value: {
          ...
          }
      }]
}]
client.createTimeSeries ({ name: formattedName, timeSeries: timeSeries }).then (() => {
        ...
    }).catch ( err => {
        ...
    })
{ Error: Request was missing field timeSeries[0].points[0].interval.endTime: The end time of the interval is required.
    at /home/admin/node_modules/grpc/src/node/src/client.js:554:15 code: 3, metadata: Metadata { _internal_repr: {} } }
```
Peter
Thanks!

**Comment by stephenplusplus** [comment]
`endTime` is expected in a raw Protobuf type called a `Timestamp`. Its definition is here: https://github.com/google/protobuf/blob/174c82d8cef27be5cb9d8491dd1e26d27898870b/src/google/protobuf/timestamp.proto#L121

To convert a JS Date object, you can use a helper function like:

```js
function dateToTimestamp(date) {
  var seconds = date.getTime() / 1000;
  var secondsRounded = Math.floor(seconds);

  return {
    seconds: secondsRounded,
    nanos: Math.floor((seconds - secondsRounded) * 1e9)
  };
}
```

To go the other way, with a response from the API:

```js
function timestampToDate(timestamp) {
  var ms = (timestamp.seconds * 1000) + (timestamp.nanos / 1e6);
  return new Date(ms);
}
```

**Comment by QTGate** [comment]
Hi Stephenplusplus,

It looks the endTime and startTime need a Object like
```js
{
    seconds: floor
    nanos: floor
}
```
That is not a typeof Date or string.

All looks working now.

Thank you so much.

Peter

**Comment by stephenplusplus** [comment]
No problem, glad it works!
