### ISSUE TITLE
storage bucket.getFiles returning "Invalid grant" on Windows

### ISSUE THREAD

**Issue by gustavomassa** [GoogleCloudPlatform/google-cloud-node#2603]
Code example: 

```
import * as googleStorage from '@google-cloud/storage';

export class FileIntegrationService {
    private storage: googleStorage;
    private config: object;
    private bucket: googleStorage;

    private constructor() {
        this.config = {
            projectId: config.default.google_project_id,
            keyFilename: config.default.root_path + config.default.google_store_key_path
        };
        this.storage = googleStorage(this.config);
        this.bucket = this.storage.bucket(config.default.google_bucket_name);
     }

public async getFilesPath(limit?: string): Promise<Webbuffet> {
        try {
            let options = undefined;
            if (limit) {
                options = {
                    projection: 'noAcl',
                    maxResults: parseInt(limit)
                };
            } else {
                options = {
                    projection: 'noAcl',
                    maxResults: 1000
                };
            }
            const result = await this.bucket.getFiles(options);
            if (!result) return Webbuffet.error(Status.FAILED);
            const data = result[2].items;
            if (!data) return Webbuffet.error(Status.ERROR_NOT_FOUND);
            const response = this.buildFileStorageResponse(data);
            if (!response) return Webbuffet.error(Status.FAILED);
            return Webbuffet.success(response);
        } catch (ex) {
            console.log(ex);
            return Webbuffet.exception(ex);
        }
    }
}

```

ERROR:
```
message: "invalid_grant"
stack: "Error: invalid_grant
    at Request._callback (c:\Projetos\Webbuffet\server\node_modules\gtoken\lib\index.js:215:34)
    at Request.self.callback (c:\Projetos\Webbuffet\server\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (c:\Projetos\Webbuffet\server\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (c:\Projetos\Webbuffet\server\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)"
__proto__: Object {name: "Error", message: ""}
```
It just stopped working on windows, but is still working on Linux (Debian).

```
Windows 10 Pro 64 bit
Node 6.11.1
@google-cloud/storage": "^1.2.1"

Working on Linux:
Debian 9.1 64 bit
Node 8.4.0
@google-cloud/storage": "^1.2.1"

```
The only difference is the Node version, but it was working fine on Windows.
It would be better if you could improve the error message.

Thank you

**Comment by stephenplusplus** [comment]
Thanks for reporting. The `invalid_grant` error is coming from the server that tries to get an authorization token that we use for all of the API requests we make.

The solution for this tends to be user/environment-based. Could you check over the conversations about this same error from past issues (https://github.com/GoogleCloudPlatform/google-cloud-node/search?q=invalid_grant&type=Issues&utf8=%E2%9C%93) and see if you find any clues? Additionally, just searching Google should return plenty of results as well.

**Comment by stephenplusplus** [comment]
@gustavomassa I'm going to close due to the age of this issue. If you are still having trouble, please let me know. And if you were able to resolve the issue, please share what worked for you-- it might help someone else. Thanks!
