### ISSUE TITLE
pubsub 0.14.5 no longer seems to work with the emulator

### ISSUE THREAD

**Issue by caseyduquettesc** [GoogleCloudPlatform/google-cloud-node#2667]
#### Issue

I went from @google-cloud-node/pubsub 0.14.2 to 0.14.4 (&5) and none of the pubsub methods seem to work with the emulator anymore. They all produce the following error.

```
TypeError: Channel's second argument must be a ChannelCredentials
      at ServiceClient.Client (node_modules/grpc/src/node/src/client.js:472:19)
      at new ServiceClient (node_modules/grpc/src/node/src/client.js:881:12)
      at node_modules/google-gax/lib/grpc.js:229:12
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:512:31)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:569:18)
      at Promise._settlePromiseCtx (node_modules/bluebird/js/release/promise.js:606:10)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:138:12)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

#### Environment details

  - OS: OSX 10.12.6
  - Node.js version: 8.5
  - npm version: 5.3.0
  - yarn version: 1.2.0
  - google-cloud-node version: pubsub v0.14.5
  - gcloud version: Google Cloud SDK [175.0.0]
  - gcloud components: 
Installed Components:
  core: [2017.10.09]
  app-engine-python: [1.9.61]
  pubsub-emulator: [2017.09.15]
  gcloud: []
  beta: [2017.09.15]
  gsutil: [4.27]
  bq: [2.0.27]

#### Steps to reproduce

`gcloud beta emulators pubsub start`

`$(gcloud beta emulators pubsub init-env)`

```javascript
const pubsub = Pubsub({
  projectId: process.env.GCLOUD_PROJECT,
  promise: require('bluebird')
});

async function getTopic (topicName) {
  try {
    const topic = await pubsub.createTopic(topicName);
    return topic[0];
  } catch (err) {
    // topic already exists.
    if (err && (err.code === 409 || err.code === 6))
      return pubsub.topic(topicName);
    throw err;
  }
}

getTopic('unit-tests');
```

**Comment by callmehiphop** [comment]
@caseyduquettesc emulator usage seems to be running fine for me, are you still experiencing this issue? Could you tell me what version of grpc you have installed?

**Comment by caseyduquettesc** [comment]
Upgrading from 0.14.2 to 0.14.5 produced this diff in my packages according to yarn.

```
diff --git a/yarn.lock b/yarn.lock
index e44f68a..4f8c410 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -69,9 +69,9 @@
     string-format-obj "^1.0.0"
     through2 "^2.0.3"
 
-"@google-cloud/pubsub@0.14.2":
-  version "0.14.2"
-  resolved "https://registry.yarnpkg.com/@google-cloud/pubsub/-/pubsub-0.14.2.tgz#1270ad4c0e8e05fdbda32f605a57281048a7b33b"
+"@google-cloud/pubsub@~0.14.5":
+  version "0.14.5"
+  resolved "https://registry.yarnpkg.com/@google-cloud/pubsub/-/pubsub-0.14.5.tgz#5e85a78b765f4cf4a01b948a551961ad7c5b2102"
   dependencies:
     "@google-cloud/common" "^0.13.0"
     "@google-cloud/common-grpc" "^0.4.0"
@@ -81,7 +81,9 @@
     google-auto-auth "^0.7.1"
     google-gax "^0.13.0"
     google-proto-files "^0.12.0"
+    grpc "^1.6.0"
     is "^3.0.1"
+    lodash.snakecase "^4.1.1"
     uuid "^3.0.1"
 
 "@google-cloud/storage@~1.2.1":
@@ -1946,6 +1948,16 @@ grpc@^1.2, grpc@^1.3.1:
     node-pre-gyp "^0.6.36"
     protobufjs "^5.0.2"
 
+grpc@^1.6.0:
+  version "1.6.6"
+  resolved "https://registry.yarnpkg.com/grpc/-/grpc-1.6.6.tgz#2051784f6bd6134681fa2c4b5e75dc82c6c23ffa"
+  dependencies:
+    arguejs "^0.2.3"
+    lodash "^4.17.4"
+    nan "^2.7.0"
+    node-pre-gyp "^0.6.38"
+    protobufjs "^5.0.2"
+
 gtoken@^1.2.1:
   version "1.2.2"
   resolved "https://registry.yarnpkg.com/gtoken/-/gtoken-1.2.2.tgz#172776a1a9d96ac09fc22a00f5be83cee6de8820"
@@ -2764,6 +2776,10 @@ lodash.restparam@^3.0.0:
   version "3.6.1"
   resolved "https://registry.yarnpkg.com/lodash.restparam/-/lodash.restparam-3.6.1.tgz#936a4e309ef330a7645ed4145986c85ae5b20805"
 
+lodash.snakecase@^4.1.1:
+  version "4.1.1"
+  resolved "https://registry.yarnpkg.com/lodash.snakecase/-/lodash.snakecase-4.1.1.tgz#39d714a35357147837aefd64b5dcbb16becd8f8d"
+
 lodash@^4.0.0, lodash@^4.13.1, lodash@^4.14.0, lodash@^4.16.0, lodash@^4.17.0, lodash@^4.17.1, lodash@^4.17.2, lodash@^4.17.4, lodash@^4.2.1, lodash@^4.3.0, lodash@~4.17.4:
   version "4.17.4"
   resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.4.tgz#78203a4d1c328ae1d86dca6460e369b57f4055ae"
@@ -3024,7 +3040,7 @@ named-placeholders@1.1.1:
   dependencies:
     lru-cache "2.5.0"
 
-nan@^2.3.0, nan@^2.3.3, nan@^2.6.2, nan@~2.7.0:
+nan@^2.3.0, nan@^2.3.3, nan@^2.6.2, nan@^2.7.0, nan@~2.7.0:
   version "2.7.0"
   resolved "https://registry.yarnpkg.com/nan/-/nan-2.7.0.tgz#d95bf721ec877e08db276ed3fc6eb78f9083ad46"
 
@@ -3080,7 +3096,7 @@ node-pre-gyp@^0.6.36:
     tar "^2.2.1"
     tar-pack "^3.4.0"
 
-node-pre-gyp@~0.6.38:
+node-pre-gyp@^0.6.38, node-pre-gyp@~0.6.38:
   version "0.6.38"
   resolved "https://registry.yarnpkg.com/node-pre-gyp/-/node-pre-gyp-0.6.38.tgz#e92a20f83416415bb4086f6d1fb78b3da73d113d"
   dependencies:
```

**Comment by caseyduquettesc** [comment]
Although, I might have 1.6.0 *and* 1.6.6...

```
bash-3.2$ yarn why grpc
yarn why v1.2.1
[1/4] 🤔  Why do we have the module "grpc"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
info Has been hoisted to "grpc"
info Reasons this module exists
   - "@google-cloud/logging-winston#@google-cloud/logging#@google-cloud/common-grpc" depends on it
   - "@google-cloud/logging-winston#@google-cloud/logging#google-gax" depends on it
info Disk size without dependencies: "56.75MB"
info Disk size with unique dependencies: "67.11MB"
info Disk size with transitive dependencies: "83.27MB"
info Number of shared dependencies: 93
```

```
bash-3.2$ yarn list grpc
yarn list v1.2.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ @google-cloud/pubsub@0.14.5
│  └─ grpc@1.6.6
└─ grpc@1.6.0
```

**Comment by caseyduquettesc** [comment]
Running `yarn upgrade` got rid of grpc 1.6.0

```
bash-3.2$ yarn list grpc
yarn list v1.2.1
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ grpc@1.6.6
```

And I no longer get this error running with the emulator
