### ISSUE TITLE
bigquery backenderror

### ISSUE THREAD

**Issue by c0b** [GoogleCloudPlatform/google-cloud-node#2687]
similar to #2661 should the client library do the retry automatically?

```js
ApiError
    at Object.parseHttpRespBody (/path/to/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:192:30)
    at Object.handleResp (/path/to/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:132:18)
    at /path/to/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:465:12
    at Request.onResponse [as _callback] (/path/to/node_modules/@google-cloud/bigquery/node_modules/retry-request/index.js:180:7)
    at Request.self.callback (/path/to/node_modules/@google-cloud/bigquery/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/path/to/node_modules/@google-cloud/bigquery/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
  code: 503,
  errors: 
   [ { domain: 'global',
       reason: 'backendError',
       message: 'Error encountered during execution. Retrying may solve the problem.' } ],
  response: undefined,
  message: 'Error encountered during execution. Retrying may solve the problem.' }
```

**Comment by callmehiphop** [comment]
AFAIK we do retry on 503s, which methods are returning this error?

**Comment by c0b** [comment]
it was on table.getmetadata was happening when api call rate close to 100 requests per second

https://cloud.google.com/bigquery/quotas#apirequests
