### ISSUE TITLE
ApiError: Not found: Files

### ISSUE THREAD

**Issue by cvanputten** [GoogleCloudPlatform/google-cloud-node#2795]
I am suddenly getting an error from 'google-cloud/bigquery' that can't find a file on gdrive. I am not calling this file in my code and I think it's coming from the @google-cloud node module. Here is the full error:
```
 { ApiError: Not found: Files /gdrive/id/1XehS5UuvCKR3fHGkeoX_7JphVc0TqGsVy6YlGRBTvZU
    at Object.parseHttpRespBody (/user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:192:30)
    at Object.handleResp (/user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:132:18)
    at /user_code/node_modules/@google-cloud/bigquery/node_modules/@google-cloud/common/src/util.js:465:12
    at Request.onResponse [as _callback] (/user_code/node_modules/@google-cloud/bigquery/node_modules/retry-request/index.js:180:7)
    at Request.self.callback (/user_code/node_modules/@google-cloud/bigquery/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/user_code/node_modules/@google-cloud/bigquery/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
  code: 404,
  errors: 
   [ { domain: 'global',
       reason: 'notFound',
       message: 'Not found: Files /gdrive/id/1XehS5UuvCKR3fHGkeoX_7JphVc0TqGsVy6YlGRBTvZU' } ],
  response: undefined,
  message: 'Not found: Files /gdrive/id/1XehS5UuvCKR3fHGkeoX_7JphVc0TqGsVy6YlGRBTvZU' }"  
 timestamp:  "2018-01-18T09:13:17.477Z
```

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-bigquery/issues/52.
